name: Semantic Release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "hello"
  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: "npm"

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Build App
  #       run: npm run build

  #     - name: Semantic Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #       run: npx semantic-release

  #     - name: Upload Build Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: react-app
  #         path: build/
  #         if-no-files-found: error
